### ISSUE TITLE
yaml

### ISSUE THREAD

**Issue by Omantik** [Brokly/ESPHOME_SBER_SBDV-00115#1]
Добрый вечер. yaml файлом не поделитесь для этой лампы?

**Comment by Brokly** [comment]
Положил файлы конфига, учитывайте, что они старого образца, времен когда либретини еще не была слита с еспхоум, поэтому их нужно подредактировать. Кроме того, я устанавливаю в лампы термосенсор, с ним, вам тоже придется разобраться.

**Comment by Omantik** [comment]
спасибо
